--- Dockerfile	2018-10-30 03:31:55.344983194 +0000
+++ Dockerfile.patched	2018-10-30 03:32:20.280219809 +0000
@@ -1,4 +1,4 @@
-FROM alpine:3.8
+FROM alpine:edge
 
 LABEL maintainer="NGINX Docker Maintainers <docker-maint@nginx.com>"
 
@@ -51,6 +51,7 @@
 		--with-http_v2_module \
 	" \
 	&& addgroup -S nginx \
+        && echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories \
 	&& adduser -D -S -h /var/cache/nginx -s /sbin/nologin -G nginx nginx \
 	&& apk add --no-cache --virtual .build-deps \
 		gcc \
@@ -136,11 +137,15 @@
 	&& ln -sf /dev/stdout /var/log/nginx/access.log \
 	&& ln -sf /dev/stderr /var/log/nginx/error.log
 
-COPY nginx.conf /etc/nginx/nginx.conf
-COPY nginx.vh.default.conf /etc/nginx/conf.d/default.conf
-
 EXPOSE 80
 
 STOPSIGNAL SIGTERM
 
+ADD config/conf.d/default.conf /etc/nginx/conf.d
+ADD config/nginx.conf /etc/nginx
+ADD entrypoint.sh /
+
+RUN chmod +x /entrypoint.sh
+
 CMD ["nginx", "-g", "daemon off;"]
+ENTRYPOINT ["/entrypoint.sh"]
